**Assignment 15: Retrieval-Augmented Generation (RAG)**

In [1]:
pip install docling

Collecting docling
  Downloading docling-2.119.0-py3-none-any.whl.metadata (11 kB)
Collecting docling-slim==2.119.0 (from docling-slim[standard]==2.119.0->docling)
  Downloading docling_slim-2.119.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (2026.6.17)
Collecting docling-core<3.0.0,>=2.90.0 (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling)
  Downloading docling_core-2.91.0-py3-none-any.whl.metadata (8.6 kB)
Collecting filetype<2.0.0,>=1.2.0 (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pluggy<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (1.6.0)
Collecting pydantic-settings<3.0.0,>=2.3.0 (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (2.13.4)
Requirement already satisfied: requests<3.0.0,>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (2.32.4)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (4.67.3)
Requirement already satisfied: accelerate<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (1.14.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (4.13.5)
Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (0.7.1)
Collecting docling-ibm-models<4,>=3.13.0 (from docling-slim[standard]==2.119.0->docling)
  Downloading docling_ibm_models-3.14.0-py3-none-any.whl.metadata (7.4 kB)
Collecting docling-parse<8.0.0,>=7.0.0 (from docling-slim[standard]==2.119.0->docling)
  Downloading docling_parse-7.12.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: httpx<1.0.0,>=0.28 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (0.28.1)
Requirement already satisfied: huggingface-hub<2,>=0.23 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (1.23.0)
Collecting mail-parser<5.0.0,>=4.1.4 (from docling-slim[standard]==2.119.0->docling)
  Downloading mail_parser-4.6.2-py3-none-any.whl.metadata (24 kB)
Collecting marko<3.0.0,>=2.1.2 (from docling-slim[standard]==2.119.0->docling)
  Downloading marko-2.2.4-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: numpy<3.0.0,>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (2.0.2)
Requirement already satisfied: openpyxl<4.0.0,>=3.1.5 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (3.1.5)
Requirement already satisfied: pillow<13.0.0,>=10.0.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (11.3.0)
Collecting polyfactory>=2.22.2 (from docling-slim[standard]==2.119.0->docling)
  Downloading polyfactory-3.3.0-py3-none-any.whl.metadata (27 kB)
Collecting pylatexenc<3.0,>=2.10 (from docling-slim[standard]==2.119.0->docling)
  Downloading pylatexenc-2.11-py2.py3-none-any.whl.metadata (3.9 kB)
Collecting pypdfium2!=4.30.1,<6.0.0,>=4.30.0 (from docling-slim[standard]==2.119.0->docling)
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 2.4 MB/s eta 0:00:00
Collecting python-docx<2.0.0,>=1.2.0 (from docling-slim[standard]==2.119.0->docling)
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: python-dotenv~=1.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (1.2.2)
Collecting python-oxmsg<0.1.0,>=0.0.2 (from docling-slim[standard]==2.119.0->docling)
  Downloading python_oxmsg-0.0.2-py3-none-any.whl.metadata (5.0 kB)
Collecting python-pptx<2.0.0,>=1.0.2 (from docling-slim[standard]==2.119.0->docling)
  Downloading python_pptx-1.0.2-py3-none-any.whl.metadata (2.5 kB)
Collecting rapidocr<4.0.0,>=3.9.1 (from docling-slim[standard]==2.119.0->docling)
  Downloading rapidocr-3.9.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: rich>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (13.9.4)
Requirement already satisfied: rtree<2.0.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (1.4.1)
Requirement already satisfied: scipy<2.0.0,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (1.16.3)
Requirement already satisfied: torch<3.0.0,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (2.11.0+cu128)
Requirement already satisfied: torchvision<1,>=0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (0.26.0+cu128)
Requirement already satisfied: typer<0.27.0,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (0.26.8)
Requirement already satisfied: websockets<17.0,>=14.0 in /usr/local/lib/python3.12/dist-packages (from docling-slim[standard]==2.119.0->docling) (15.0.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=1.0.0->docling-slim[standard]==2.119.0->docling) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=1.0.0->docling-slim[standard]==2.119.0->docling) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=1.0.0->docling-slim[standard]==2.119.0->docling) (6.0.3)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=1.0.0->docling-slim[standard]==2.119.0->docling) (0.8.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->docling-slim[standard]==2.119.0->docling) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->docling-slim[standard]==2.119.0->docling) (4.16.0)
Requirement already satisfied: jsonschema<5.0.0,>=4.16.0 in /usr/local/lib/python3.12/dist-packages (from docling-core<3.0.0,>=2.90.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (4.26.0)
Collecting jsonref<2.0.0,>=1.1.0 (from docling-core<3.0.0,>=2.90.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling)
  Downloading jsonref-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: tabulate<0.11.0,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from docling-core<3.0.0,>=2.90.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (0.9.0)
Requirement already satisfied: pandas<4.0.0,>=2.1.4 in /usr/local/lib/python3.12/dist-packages (from docling-core<3.0.0,>=2.90.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (2.2.2)
Collecting latex2mathml<4.0.0,>=3.77.0 (from docling-core<3.0.0,>=2.90.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling)
  Downloading latex2mathml-3.81.0-py3-none-any.whl.metadata (15 kB)
Collecting doclang<0.8,>=0.7 (from docling-core<3.0.0,>=2.90.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling)
  Downloading doclang-0.7.3-py3-none-any.whl.metadata (4.6 kB)
Collecting semchunk<4.0.0,>=2.2.0 (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.119.0->docling)
  Downloading semchunk-3.2.5-py3-none-any.whl.metadata (14 kB)
Collecting tree-sitter<0.27.0,>=0.25.0 (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.119.0->docling)
  Downloading tree_sitter-0.26.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting tree-sitter-python>=0.23.6 (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.119.0->docling)
  Downloading tree_sitter_python-0.25.0-cp310-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (1.9 kB)
Collecting tree-sitter-c>=0.23.4 (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.119.0->docling)
  Downloading tree_sitter_c-0.24.2-cp310-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting tree-sitter-javascript>=0.23.1 (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.119.0->docling)
  Downloading tree_sitter_javascript-0.25.0-cp310-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (2.2 kB)
Collecting tree-sitter-typescript>=0.23.2 (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.119.0->docling)
  Downloading tree_sitter_typescript-0.23.2-cp39-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Requirement already satisfied: transformers!=5.0.*,!=5.1.*,!=5.2.*,!=5.3.*,<6.0.0,>=4.34.0 in /usr/local/lib/python3.12/dist-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.119.0->docling) (5.13.1)
Collecting jsonlines<5.0.0,>=3.1.0 (from docling-ibm-models<4,>=3.13.0->docling-slim[standard]==2.119.0->docling)
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28->docling-slim[standard]==2.119.0->docling) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28->docling-slim[standard]==2.119.0->docling) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28->docling-slim[standard]==2.119.0->docling) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28->docling-slim[standard]==2.119.0->docling) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.119.0->docling) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.119.0->docling) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.119.0->docling) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.119.0->docling) (1.5.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl<4.0.0,>=3.1.5->docling-slim[standard]==2.119.0->docling) (2.0.0)
Collecting faker>=5.0.0 (from polyfactory>=2.22.2->docling-slim[standard]==2.119.0->docling)
  Downloading faker-40.36.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (0.4.2)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx<2.0.0,>=1.2.0->docling-slim[standard]==2.119.0->docling) (6.1.1)
Collecting olefile (from python-oxmsg<0.1.0,>=0.0.2->docling-slim[standard]==2.119.0->docling)
  Downloading olefile-0.47-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting XlsxWriter>=0.5.7 (from python-pptx<2.0.0,>=1.0.2->docling-slim[standard]==2.119.0->docling)
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Collecting pyclipper>=1.2.0 (from rapidocr<4.0.0,>=3.9.1->docling-slim[standard]==2.119.0->docling)
  Downloading pyclipper-1.4.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (8.6 kB)
Requirement already satisfied: opencv_python>=4.5.1.48 in /usr/local/lib/python3.12/dist-packages (from rapidocr<4.0.0,>=3.9.1->docling-slim[standard]==2.119.0->docling) (5.0.0.93)
Requirement already satisfied: six>=1.15.0 in /usr/local/lib/python3.12/dist-packages (from rapidocr<4.0.0,>=3.9.1->docling-slim[standard]==2.119.0->docling) (1.17.0)
Requirement already satisfied: Shapely!=2.0.4,>=1.7.1 in /usr/local/lib/python3.12/dist-packages (from rapidocr<4.0.0,>=3.9.1->docling-slim[standard]==2.119.0->docling) (2.1.2)
Requirement already satisfied: omegaconf!=2.2.1 in /usr/local/lib/python3.12/dist-packages (from rapidocr<4.0.0,>=3.9.1->docling-slim[standard]==2.119.0->docling) (2.3.1)
Collecting colorlog (from rapidocr<4.0.0,>=3.9.1->docling-slim[standard]==2.119.0->docling)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.2->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.2->docling-slim==2.119.0->docling-slim[standard]==2.119.0->docling) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.0.0->docling-slim[standard]==2.119.0->docling) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.0.0->docling-slim[standard]==2.119.0->docling) (2.20.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3.0.0,>=2.2.2->docling-slim[standard]==2.119.0->docling) (12.8.93)

In [2]:
pip install llama_index

Collecting llama_index
  Downloading llama_index-0.14.23-py3-none-any.whl.metadata (14 kB)
Collecting llama-index-core<0.15.0,>=0.14.23 (from llama_index)
  Downloading llama_index_core-0.14.23-py3-none-any.whl.metadata (2.6 kB)
Collecting llama-index-embeddings-openai<0.7,>=0.6.0 (from llama_index)
  Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl.metadata (401 bytes)
Collecting llama-index-llms-openai<0.8,>=0.7.0 (from llama_index)
  Downloading llama_index_llms_openai-0.7.10-py3-none-any.whl.metadata (3.0 kB)
Collecting nltk>=3.9.3 (from llama_index)
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (3.14.1)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (0.22.1)
Collecting banks<3,>=2.3.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading banks-2.5.0-py3-none-any.whl.metadata (12 kB)
Collecting dataclasses-json (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting dirtyjson<2,>=1.0.8 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: filetype<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2025.3.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (0.28.1)
Collecting llama-index-workflows<3,>=2.14.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading llama_index_workflows-2.23.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.0.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (11.3.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (4.10.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.13.4)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.32.4)
Collecting setuptools>=80.9.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (0.13.0)
Collecting tinytag>=2.2.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading tinytag-2.3.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: tqdm<5,>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (4.67.3)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (4.16.0)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.2.2)
Requirement already satisfied: openai>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (2.45.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (0.7.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (2025.11.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.24.2)
Collecting griffe (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading griffe-2.1.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.1.6)
Collecting llama-index-instrumentation>=0.4.3 (from llama-index-workflows<3,>=2.14.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (0.16.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.23->llama_index) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.5.3)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.12/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core<0.15.0,>=0.14.23->llama_index) (26.2)
Collecting griffecli==2.1.0 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading griffecli-2.1.0-py3-none-any.whl.metadata (1.2 kB)
Collecting griffelib==2.1.0 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading griffelib-2.1.0-py3-none-any.whl.metadata (1.3 kB)
Collecting colorama>=0.4 (from griffecli==2.1.0->griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.0.3)
Downloading llama_index-0.14.23-py3-none-any.whl (7.1 kB)
Downloading llama_index_core-0.14.23-py3-none-any.whl (11.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 92.9 MB/s eta 0:00:00
Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl (7.7 kB)
Downloading llama_index_llms_openai-0.7.10-py3-none-any.whl (28 kB)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 83.4 MB/s eta 0:00:00
Downloading banks-2.5.0-py3-none-any.whl (38 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading dirtyjson-1.0.8-py3-none-any.whl (25 kB)
Downloading llama_index_workflows-2.23.1-py3-none-any.whl (164 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.9/164.9 kB 14.9 MB/s eta 0:00:00
Downloading setuptools-84.0.0-py3-none-any.whl (818 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 818.2/818.2 kB 48.0 MB/s eta 0:00:00
Downloading tinytag-2.3.0-py3-none-any.whl (37 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl (16 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 7.6 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading griffe-2.1.0-py3-none-any.whl (5.1 kB)
Downloading griffecli-2.1.0-py3-none-any.whl (9.5 kB)
Downloading griffelib-2.1.0-py3-none-any.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.6/142.6 kB 11.6 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: dirtyjson, tinytag, setuptools, nltk, mypy-extensions, marshmallow, griffelib, deprecated, colorama, typing-inspect, griffecli, llama-index-instrumentation, griffe, dataclasses-json, llama-index-workflows, banks, llama-index-core, llama-index-llms-openai, llama-index-embeddings-openai, llama_index
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: nltk
    Found existing installation: nltk 3.9.1
    Uninstalling nltk-3.9.1:
      Successfully uninstalled nltk-3.9.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
torch 2.11.0+cu128 requires setuptools<82, but you have setuptools 84.0.0 which is incompatible.
Successfully installed banks-2.5.0 colorama-0.4.6 dataclasses-json-0.6.7 deprecated-1.3.1 dirtyjson-1.0.8 griffe-2.1.0 griffecli-2.1.0 griffelib-2.1.0 llama-index-core-0.14.23 llama-index-embeddings-openai-0.6.0 llama-index-instrumentation-0.5.0 llama-index-llms-openai-0.7.10 llama-index-workflows-2.23.1 llama_index-0.14.23 marshmallow-3.26.2 mypy-extensions-1.1.0 nltk-3.10.3 setuptools-84.0.0 tinytag-2.3.0 typing-inspect-0.9.0

In [1]:
pip install langchain langchain-community langchain-huggingface faiss-cpu sentence-transformers

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.3.13)
Collecting langchain-community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain-huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Collecting faiss-cpu
  Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.9 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.4.9)
Requirement already satisfied: langgraph<1.3.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.13.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.10.2)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.15.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (1.23.0)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.22.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.9->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.9->langchain) (0.0.18)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.9->langchain) (0.17.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (3.8.1)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.14.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.6.17)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.3)
Collecting setuptools<82 (from torch>=1.11.0->sentence-transformers)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.6)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.9->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.5->langchain) (1.12.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 67.2 MB/s eta 0:00:00
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 90.2 MB/s eta 0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 68.1 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 8.7 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 61.6 MB/s eta 0:00:00
Installing collected packages: setuptools, requests, httpx-sse, faiss-cpu, langchain-text-splitters, langchain-huggingface, langchain-classic, langchain-community
  Attempting uninstall: setuptools
    Found existing installation: setuptools 84.0.0
    Uninstalling setuptools-84.0.0:
      Successfully uninstalled setuptools-84.0.0
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
Successfully installed faiss-cpu-1.15.0 httpx-sse-0.4.3 langchain-classic-1.0.8 langchain-community-0.4.2 langchain-huggingface-1.2.2 langchain-text-splitters-1.1.2 requests-2.34.2 setuptools-81.0.0

In [20]:
pip install --upgrade --force-reinstall langchain langchain-community

Collecting langchain
  Downloading langchain-1.3.15-py3-none-any.whl.metadata (6.1 kB)
Collecting langchain-community
  Using cached langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain-core<2.0.0,>=1.5.4 (from langchain)
  Using cached langchain_core-1.5.4-py3-none-any.whl.metadata (4.8 kB)
Collecting langgraph<1.3.0,>=1.2.11 (from langchain)
  Downloading langgraph-1.2.11-py3-none-any.whl.metadata (4.9 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.4/109.4 kB 9.8 MB/s eta 0:00:00
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community)
  Downloading aiohttp-3.14.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Using cached httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)
  Using cached langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting langsmith<1.0.0,>=0.1.125 (from langchain-community)
  Downloading langsmith-0.10.18-py3-none-any.whl.metadata (22 kB)
Collecting numpy>=1.26.2 (from langchain-community)
  Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Using cached pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting pyyaml<7.0.0,>=5.3.0 (from langchain-community)
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sqlalchemy<3.0.0,>=1.4.0 (from langchain-community)
  Downloading sqlalchemy-2.0.52-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-community)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting typing_extensions>=4.4 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading yarl-1.24.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.0/104.0 kB 8.4 MB/s eta 0:00:00
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)
  Using cached langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.5.4->langchain)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain-core<2.0.0,>=1.5.4->langchain)
  Downloading langchain_protocol-0.0.18-py3-none-any.whl.metadata (2.4 kB)
Collecting packaging>=23.2.0 (from langchain-core<2.0.0,>=1.5.4->langchain)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.5.4->langchain)
  Downloading uuid_utils-0.17.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.2 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading langgraph_sdk-0.4.2-py3-none-any.whl.metadata (3.6 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading xxhash-4.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting anyio>=3.5.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting distro>=1.7.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx<1,>=0.23.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting orjson>=3.9.14 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 4.8 MB/s eta 0:00:00
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting sniffio>=1.1 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting websockets>=15.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading websockets-17.0.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.3 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain-community)
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Collecting charset_normalizer<4,>=2 (from requests<3.0.0,>=2.32.5->langchain-community)
  Downloading charset_normalizer-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 4.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.32.5->langchain-community)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests<3.0.0,>=2.32.5->langchain-community)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3.0.0,>=2.32.5->langchain-community)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting greenlet>=1 (from sqlalchemy<3.0.0,>=1.4.0->langchain-community)
  Downloading greenlet-3.5.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.5.4->langchain)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain)
  Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting websockets>=15.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading websockets-15.0.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Downloading langchain-1.3.15-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.0/147.0 kB 15.1 MB/s eta 0:00:00
Using cached langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
Downloading aiohttp-3.14.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 90.8 MB/s eta 0:00:00
Using cached httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Using cached langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
Using cached langchain_core-1.5.4-py3-none-any.whl (565 kB)
Downloading langgraph-1.2.11-py3-none-any.whl (248 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.9/248.9 kB 28.1 MB/s eta 0:00:00
Downloading langsmith-0.10.18-py3-none-any.whl (735 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 735.3/735.3 kB 56.8 MB/s eta 0:00:00
Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 100.0 MB/s eta 0:00:00
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.3/472.3 kB 43.4 MB/s eta 0:00:00
Downloading pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 94.0 MB/s eta 0:00:00
Using cached pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 48.7 MB/s eta 0:00:00
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading sqlalchemy-2.0.52-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 115.6 MB/s eta 0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading anyio-4.14.2-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.8/125.8 kB 15.7 MB/s eta 0:00:00
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 7.5 MB/s eta 0:00:00
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.0/137.0 kB 16.6 MB/s eta 0:00:00
Downloading charset_normalizer-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.5/247.5 kB 28.1 MB/s eta 0:00:00
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 22.0 MB/s eta 0:00:00
Downloading greenlet-3.5.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (621 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 621.4/621.4 kB 48.0 MB/s eta 0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.1 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 9.0 MB/s eta 0:00:00
Downloading idna-3.18-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 7.3 MB/s eta 0:00:00
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langchain_protocol-0.0.18-py3-none-any.whl (7.2 kB)
Using cached langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 6.6 MB/s eta 0:00:00
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 4.1 MB/s eta 0:00:00
Downloading langgraph_sdk-0.4.2-py3-none-any.whl (160 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.5/160.5 kB 18.7 MB/s eta 0:00:00
Downloading multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.3/256.3 kB 28.9 MB/s eta 0:00:00
Downloading orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.0/134.0 kB 15.6 MB/s eta 0:00:00
Downloading packaging-26.3-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 15.8 MB/s eta 0:00:00
Downloading propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 7.4 MB/s eta 0:00:00
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 6.1 MB/s eta 0:00:00
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 5.0 MB/s eta 0:00:00
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 15.8 MB/s eta 0:00:00
Downloading uuid_utils-0.17.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (320 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.2/320.2 kB 34.6 MB/s eta 0:00:00
Downloading websockets-15.0.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (182 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.5/182.5 kB 21.3 MB/s eta 0:00:00
Downloading xxhash-4.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (261 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.5/261.5 kB 30.2 MB/s eta 0:00:00
Downloading yarl-1.24.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (109 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.8/109.8 kB 13.5 MB/s eta 0:00:00
Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 125.0 MB/s eta 0:00:00
Downloading jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.6/212.6 kB 24.2 MB/s eta 0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, urllib3, typing_extensions, tenacity, sniffio, pyyaml, python-dotenv, propcache, packaging, ormsgpack, orjson, numpy, multidict, jsonpointer, idna, httpx-sse, h11, greenlet, frozenlist, distro, charset_normalizer, certifi, attrs, annotated-types, aiohappyeyeballs, yarl, typing-inspection, sqlalchemy, requests, pydantic-core, langchain-protocol, jsonpatch, httpcore, anyio, aiosignal, requests-toolbelt, pydantic, httpx, aiohttp, pydantic-settings, langsmith, langchain-core, langgraph-sdk, langgraph-checkpoint, langchain-text-splitters, langgraph-prebuilt, langchain-classic, langgraph, langchain-community, langchain
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.25.0
    Uninstalling zstandard-0.25.0:
      Successfully uninstalled zstandard-0.25.0
  Attempting uninstall: xxhash
    Found existing installation: xxhash 3.8.1
    Uninstalling xxhash-3.8.1:
      Successfully uninstalled xxhash-3.8.1
  Attempting uninstall: websockets
    Found existing installation: websockets 15.0.1
    Uninstalling websockets-15.0.1:
      Successfully uninstalled websockets-15.0.1
  Attempting uninstall: uuid-utils
    Found existing installation: uuid_utils 0.17.0
    Uninstalling uuid_utils-0.17.0:
      Successfully uninstalled uuid_utils-0.17.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.3.1
    Uninstalling sniffio-1.3.1:
      Successfully uninstalled sniffio-1.3.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 1.2.2
    Uninstalling python-dotenv-1.2.2:
      Successfully uninstalled python-dotenv-1.2.2
  Attempting uninstall: propcache
    Found existing installation: propcache 0.5.2
    Uninstalling propcache-0.5.2:
      Successfully uninstalled propcache-0.5.2
  Attempting uninstall: packaging
    Found existing installation: packaging 26.2
    Uninstalling packaging-26.2:
      Successfully uninstalled packaging-26.2
  Attempting uninstall: ormsgpack
    Found existing installation: ormsgpack 1.12.2
    Uninstalling ormsgpack-1.12.2:
      Successfully uninstalled ormsgpack-1.12.2
  Attempting uninstall: orjson
    Found existing installation: orjson 3.11.9
    Uninstalling orjson-3.11.9:
      Successfully uninstalled orjson-3.11.9
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: multidict
    Found existing installation: multidict 6.7.1
    Uninstalling multidict-6.7.1:
      Successfully uninstalled multidict-6.7.1
  Attempting uninstall: jsonpointer
    Found existing installation: jsonpointer 3.1.1
    Uninstalling jsonpointer-3.1.1:
      Successfully uninstalled jsonpointer-3.1.1
  Attempting uninstall: idna
    Found existing installation: idna 3.18
    Uninstalling idna-3.18:
      Successfully uninstalled idna-3.18
  Attempting uninstall: httpx-sse
    Found existing installation: httpx-sse 0.4.3
    Uninstalling httpx-sse-0.4.3:
      Successfully uninstalled httpx-sse-0.4.3
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.5.3
    Uninstalling greenlet-3.5.3:
      Successfully uninstalled greenlet-3.5.3
  Attempting uninstall: frozenlist
    Found existing installation: frozenlist 1.8.0
    Uninstalling frozenlist-1.8.0:
      Successfully uninstalled frozenlist-1.8.0
  Attempting uninstall: distro

In [34]:
pip install langchain_ollama

Collecting langchain_ollama
  Downloading langchain_ollama-1.1.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.21 in /usr/local/lib/python3.12/dist-packages (from langchain_ollama) (1.5.4)
Collecting ollama<1.0.0,>=0.6.1 (from langchain_ollama)
  Downloading ollama-0.6.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (0.10.18)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (26.3)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (2.13.4)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain_ollama) (0.17.0)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama<1.0.0,>=0.6.1->langchain_ollama) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain_ollama) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain_ollama) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain_ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain_ollama) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain_ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (1.9.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (4.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (3.5.0)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain_ollama) (2.7.0)
Downloading langchain_ollama-1.1.0-py3-none-any.whl (31 kB)
Downloading ollama-0.6.2-py3-none-any.whl (15 kB)
Installing collected packages: ollama, langchain_ollama
Successfully installed langchain_ollama-1.1.0 ollama-0.6.2

In [1]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

###PDF Loading and Parsing

In [2]:
from docling.document_converter import DocumentConverter
import os

converter = DocumentConverter()
result = converter.convert("/content/the-state-of-ai-how-organizations-are-rewiring-to-capture-value_final.pdf")

# Define the output directory
output_dir = "output_documents"
os.makedirs(output_dir, exist_ok=True)  # Ensure the directory exists

# Define output file path
output_path = os.path.join(output_dir, "converted_document_infosys_pr_q1_2026.md")

# Save as Markdown
with open(output_path, "w", encoding="utf-8") as f:
    f.write(result.document.export_to_markdown())

print(f"Document saved at: {output_path}")

[INFO] 2026-08-14 06:24:12,133 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-08-14 06:24:12,137 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-08-14 06:24:12,141 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.2/torch/PP-OCRv6/det/PP-OCRv6_det_small.pth
[INFO] 2026-08-14 06:24:14,003 [RapidOCR] download_file.py:82: Download size: 9.77MB
[INFO] 2026-08-14 06:24:14,091 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/PP-OCRv6_det_small.pth
[INFO] 2026-08-14 06:24:14,095 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/PP-OCRv6_det_small.pth
[INFO] 2026-08-14 06:24:14,586 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-08-14 06:24:14,587 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-08-14 06:24:14,589 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.2/torch/PP-OCRv4/cls/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-08-14 06:24:16,120 [RapidOCR] download_file.py:82: Download size: 0.56MB
[INFO] 2026-08-14 06:24:16,131 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-08-14 06:24:16,134 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-08-14 06:24:16,242 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-08-14 06:24:16,243 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-08-14 06:24:16,245 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.2/torch/PP-OCRv6/rec/PP-OCRv6_rec_small.pth
[INFO] 2026-08-14 06:24:18,178 [RapidOCR] download_file.py:82: Download size: 20.34MB
[INFO] 2026-08-14 06:24:18,385 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/PP-OCRv6_rec_small.pth
[INFO] 2026-08-14 06:24:18,389 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/PP-OCRv6_rec_small.pth
[INFO] 2026-08-14 06:24:18,634 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.2/paddle/PP-OCRv6/rec/PP-OCRv6_rec_small/ppocrv6_dict.txt
[INFO] 2026-08-14 06:24:20,123 [RapidOCR] download_file.py:82: Download size: 0.07MB
[INFO] 2026-08-14 06:24:20,873 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ppocrv6_dict.txt
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

W0814 06:25:24.448000 1848 torch/_inductor/utils.py:1731] [2/0_1] Not enough SMs to use max_autotune_gemm mode
/usr/local/lib/python3.12/dist-packages/torch/nn/modules/conv.py:548: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /pytorch/aten/src/ATen/native/Convolution.cpp:1024.)
  return F.conv2d(
WARNING:docling.models.stages.ocr.rapid_ocr_model:RapidOCR returned empty result!
WARNING:docling.models.stages.ocr.rapid_ocr_model:RapidOCR returned empty result!
WARNING:docling.models.stages.ocr.rapid_ocr_model:RapidOCR returned empty result!
[WARNING] 2026-08-14 06:28:09,827 [RapidOCR] main.py:132: The text detection result is empty
WARNING:docling.models.stages.ocr.rapid_ocr_model:RapidOCR returned empty result!

Document saved at: output_documents/converted_document_infosys_pr_q1_2026.md

In [3]:
import re

def display_md_structure(md_file_path):
    with open(md_file_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    print("Document Structure")
    print("-" * 40)

    for i, line in enumerate(lines, start=1):
        # Match Markdown headings (#, ##, ###)
        heading_match = re.match(r'^(#+)\s+(.*)', line)
        if heading_match:
            level = len(heading_match.group(1))   # number of # indicates heading level
            heading = heading_match.group(2).strip()
            print(f"Line {i}: {'  ' * (level-1)}{heading}")

        # If page numbers are embedded (e.g., "Page 3"), you can detect them:
        page_match = re.match(r'^Page\s+(\d+)', line.strip(), re.IGNORECASE)
        if page_match:
            page_num = page_match.group(1)
            print(f"--> Found Page {page_num} marker at line {i}")

# Example usage
display_md_structure("/content/output_documents/converted_document_infosys_pr_q1_2026.md")

Document Structure
----------------------------------------
Line 3:   The state of AI AI e of
Line 21:   How companies are organizing their gen AI deploymentand who's in charge
Line 27:   Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.
Line 51:   Organizations are selectively centralizing elements of their AI deployment
Line 57:   Exhibit 1 &lt;GenAI2024-2&gt; Exhibit &lt;1&gt; of &lt;14&gt;
Line 59:   Risk and data governance are two of the most centralized elements of deploying AI solutions, whereas tech talent is often hybrid.
Line 71:   Twenty-seven percent of
Line 75:   Organizations vary widely in how they monitor gen AI outputs
Line 93:   Organizations are addressing more gen-AI-related risks
Line 101:   Respondents report increasing mitigation of inaccuracy, intellectual property infringement, and privacy risks related to use of gen AI.
Line 115:   Alex Singla Senior partner and global coleader of QuantumBlack, AI by McKinsey
Line 125:   Less than one-third of respondents report that their organizations are following most of the 12 adoption and scaling practices for gen AI.
Line 127:   Best practices for adoption and scaling can enable value, and companies are beginning to follow them
Line 137:   Exhibit 4 &lt;GenAI2024-2&gt;
Line 141:   Larger organizations are following more adoption and scaling best practices for gen AI deployment than are smaller organizations.
Line 151:   Bryce Hall
Line 161:   AI is shifting the skills that organizations need
Line 165:   Half of respondents whose organizations use AI say their employers will need more data scientists over the next year.
Line 171:   Exhibit 5 &lt;GenAI2024-2&gt; Exhibit &lt;5&gt; of &lt;14&gt;
Line 173:   Smaller shares of respondents report difficulty in hiring for AI-related roles, compared with previous years.
Line 181:   Many respondents expect to undertake more AI-related reskilling in the next three years than they conducted in the past year.
Line 189:   Exhibit 6 &lt;GenAI2024-2&gt; Exhibit &lt;6&gt; of &lt;14&gt;
Line 211:   Respondents most often predict that gen AI use will lead to decreased head count in service operations and supply chain management.
Line 223:   AI use continues to climb
Line 233:   Exhibit 8 &lt;GenAI2024-2&gt; Exhibit &lt;8&gt; of &lt;14&gt;
Line 237:   Organizations' use of AI has accelerated markedly in the past year, after years of little meaningful change.
Line 239:   Organizations that use AI in at least 1 business function, ¹ % of respondents
Line 249:   Exhibit 9 &lt;GenAI2024-2&gt; Exhibit &lt;9&gt; of &lt;14&gt;
Line 251:   Organizations are increasingly using AI in multiple functions.
Line 271:   Exhibit 10 &lt;GenAI2024-2&gt; Exhibit &lt;10&gt; of &lt;14&gt;
Line 273:   Organizations across industries have begun to use gen AI in marketing and sales, though other uses vary by industry.
Line 275:   Business functions in which respondents' organizations are regularly using gen AI, by industry, 1
Line 283:   C-level executives are using gen AI more than others
Line 287:   Exhibit
Line 289:   Respondents are much more likely now than in 2023 and in early 2024 to say they are using gen AI.
Line 291:   Personal experience with gen AI tools, in 2023, first half of 2024, and second half of 2024, ¹ % of respondents
Line 307:   Respondents are much more likely now than in 2023 and in early 2024 to say they are using gen AI.
Line 309:   Personal experience with gen AI tools, in 2023, first half of 2024, and second half of 2024, ¹ % of respondents
Line 315:   Personal experience with gen AI tools, in 2023, first half of 2024, and second half of 2024, ¹ % of respondents
Line 323:   More than one-third of respondents say their organizations use gen AI to create images, and more than onequarter use it to create computer code.
Line 329:   Exhibit 11 &lt;GenAI2024-2&gt; Exhibit &lt;11&gt; of &lt;14&gt;
Line 331:   While text is the type of content that organizations are most commonly creating with gen AI, they are also experimenting with other modalities.
Line 345:   Organizations increasingly see gen AI's effects on revenues in the business units using the technology.
Line 359:   Respondents increasingly report cost reductions from gen AI within business units using the technology.
Line 369:   Michael Chui
Line 385:   About the research

###Chunk Creation

In [4]:
from llama_index.core import Settings
from llama_index.core.text_splitter import SentenceSplitter

splitter = SentenceSplitter(
    chunk_size=500,
    chunk_overlap=100
)

In [5]:
from pathlib import Path
md_path = "/content/output_documents/converted_document_infosys_pr_q1_2026.md"
markdown_text = Path(md_path).read_text(
    encoding="utf-8"
)
heading_pattern = re.compile(
    r"^(#{1,6})\s+(.*)$",
    re.MULTILINE
)

matches = list(
    heading_pattern.finditer(markdown_text)
)

print("Number of headings:", len(matches))

Number of headings: 46

In [6]:
chunks = []

heading_stack = []

for i, match in enumerate(matches):

    # -----------------------------------------
    # Heading information
    # -----------------------------------------

    heading_level = len(match.group(1))
    heading_text = match.group(2).strip()

    # -----------------------------------------
    # Maintain heading hierarchy
    # -----------------------------------------

    heading_stack = heading_stack[:heading_level - 1]
    heading_stack.append(heading_text)

    section = " > ".join(heading_stack)

    # -----------------------------------------
    # Find section text
    # -----------------------------------------

    start = match.end()

    if i + 1 < len(matches):
        end = matches[i + 1].start()
    else:
        end = len(markdown_text)

    section_text = markdown_text[start:end].strip()

    # Skip empty sections
    if not section_text:
        continue

    # -----------------------------------------
    # Sentence-based chunking
    # -----------------------------------------

    text_chunks = splitter.split_text(section_text)

    # -----------------------------------------
    # Store chunks + metadata
    # -----------------------------------------

    for chunk_text in text_chunks:

        chunks.append({
            "chunk_id": f"chunk_{len(chunks)}",
            "section": section,
            "heading": heading_text,
            "heading_level": heading_level,
            "text": chunk_text,
            "source": md_path,
            "word_count": len(chunk_text.split())
        })

In [7]:
print("Total chunks:", len(chunks))

for chunk in chunks[:5]:

    print("=" * 100)

    print("Chunk ID      :", chunk["chunk_id"])
    print("Section       :", chunk["section"])
    print("Heading       :", chunk["heading"])
    print("Heading Level :", chunk["heading_level"])
    print("Word Count    :", chunk["word_count"])
    print("Source        :", chunk["source"])

    print("\nText:")
    print(chunk["text"])

    print()

Total chunks: 37
====================================================================================================
Chunk ID      : chunk_0
Section       : The state of AI AI e of
Heading       : The state of AI AI e of
Heading Level : 2
Word Count    : 208
Source        : /content/output_documents/converted_document_infosys_pr_q1_2026.md

Text:
How organizations are rewiring to capture value

Alex Singla Alexander Sukharevsky Lareina Yee Michael Chui Bryce Hall

March 2025

Organizations are beginning to create the structures and processes that lead to meaningful value from gen AI. While still in early days, companies are redesigning workflows, elevating governance, and mitigating more risks.

<!-- image -->

rganizations are starting to make organizational changes designed to generate future value from gen AI, and large companies are leading the way. The latest McKinsey Global Survey on AI finds

that organizations are beginning to take steps that drive bottom-line impact-for example, redesigning workflows as they deploy gen AI and putting senior leaders in critical roles, such as overseeing AI governance. The findings also show that organizations are working to mitigate a growing set of gen-AI-related risks and are hiring for new AI-related roles while they retrain employees to participate in AI deployment. Companies with at least $500 million in annual revenue are changing more quickly than smaller organizations. Overall, the use of AI-that is, gen AI as well as analytical AI-continues to build momentum: More than three-quarters of respondents now say that their organizations use AI in at least one business function. The use of gen AI in particular is rapidly increasing.

O

====================================================================================================
Chunk ID      : chunk_1
Section       : The state of AI AI e of > How companies are organizing their gen AI deploymentand who's in charge
Heading       : How companies are organizing their gen AI deploymentand who's in charge
Heading Level : 2
Word Count    : 209
Source        : /content/output_documents/converted_document_infosys_pr_q1_2026.md

Text:
Our survey analyses show that a CEO's oversight of AI governance-that is, the policies, processes, and technology necessary to develop and deploy AI systems responsibly-is one element most correlated with higher self-reported bottom-line impact from an organization's gen AI use. 1 That's particularly true at larger companies, where CEO oversight is the element with the most impact on EBIT attributable to gen AI. Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance, though the share is smaller at larger organizations with $500 million or more in annual revenues, and 17 percent say AI governance is overseen by their board of directors. In many cases, AI governance is jointly owned: On average, respondents report that two leaders are in charge.

The value of AI comes from rewiring how companies run, and the latest survey shows that, out of 25 attributes tested for organizations of all sizes, the redesign of workflows has the biggest effect on an organization's ability to see EBIT impact from its use of gen AI. Organizations are beginning to reshape their workflows as they deploy gen AI. Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.

====================================================================================================
Chunk ID      : chunk_2
Section       : The state of AI AI e of > Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.
Heading       : Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.
Heading Level : 2
Word Count    : 358
Source        : /content/output_documents/converted_document_infosys_pr_q1_2026.md

Text:
1 The correlation analyses considered 25 attributes and the reported effect of gen AI use on organizations' EBIT, and using the Johnson's Relative Weights regression analysis yielded an R-squared of 0.20. The attributes included which leaders oversee AI governance at organizations, how organizations are managing the time saved by gen AI deployment (for example, assigning completely new activities and fewer hours to employees, reducing head count), whether organizations have fundamentally redesigned at least some of their workflows as a result of gen AI deployment, and whether they have adopted each of 12 gen AI adoption and scaling best practices: 1) establishing a dedicated team to drive gen AI adoption (for example, a project management office, transformation office, or dedicated adoption and scaling team); 2) having regular internal communications about the value created by their gen AI solutions to build awareness and momentum; 3) having senior leaders who are actively engaged in driving gen AI adoption, including role modeling the use of gen AI; 4) embedding gen AI solutions into business processes effectively (for example, changing frontline employees' processes, creating user interfaces to incorporate gen AI solutions); 5) establishing role-based capability training courses to make sure employees at each level know how to use gen AI capabilities appropriately; 6) creating a comprehensive approach to foster trust among employees in our use of gen AI (for example, understanding primary sources, mitigating inaccuracies); 7) having a mechanism to incorporate feedback on the performance of gen AI solutions and improve them over time; 8) establishing a clearly defined road map to drive adoption of gen AI solutions (for example, with phased rollouts across teams and business units); 9) establishing a compelling change story about the need for gen AI adoption; 10) tracking well-defined KPIs for gen AI solutions, enabling insights into their adoption and ROI; 11) establishing employee incentives that reinforce gen AI adoption; and 12) creating a comprehensive approach to foster trust among customers in our use of gen AI (for example, transparency on regulatory compliance, use of customer data).

Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.

====================================================================================================
Chunk ID      : chunk_3
Section       : The state of AI AI e of > Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.
Heading       : Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.
Heading Level : 2
Word Count    : 234
Source        : /content/output_documents/converted_document_infosys_pr_q1_2026.md

Text:
Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.

<!-- image -->

<!-- image -->

6

McKinsey commentary

Alexander Sukharevsky

Senior partner and global coleader of QuantumBlack, AI by McKinsey

The more we see organizations using AI, the more we recognize that it takes a topdown process to really move the needle. Effective AI implementation starts with a fully committed C-suite and, ideally, an engaged board. Many companies' instinct is to delegate implementation to the IT or digital department, but over and over again, this turns out to be a recipe for failure.

There are several reasons for this. The first is that getting real value out of AI requires transformation, not just new technology. It's a question of successful change management and mobilization, which is why C-suite leadership is essential. It's also a potentially expensive transformation, requiring intensive use of sometimes scarce resources and talent. A lot rides on how those resources are made available, and that's an executive-level call requiring nuanced decision-making that reflects the balance organizations must strike between efficient resource use and broad empowerment-a balance that must be constantly reevaluated as the technology and organization evolve.

As organizations become more fluent with AI, it will essentially become embedded in all functions, leaving leadership to focus on higher-level tasks like impact monitoring and talent development rather than on implementation.

====================================================================================================
Chunk ID      : chunk_4
Section       : The state of AI AI e of > Organizations are selectively centralizing elements of their AI deployment
Heading       : Organizations are selectively centralizing elements of their AI deployment
Heading Level : 2
Word Count    : 112
Source        : /content/output_documents/converted_document_infosys_pr_q1_2026.md

Text:
The survey findings also shed light on how organizations are structuring their AI deployment efforts. Some essential elements for deploying AI tend to be fully or partially centralized (Exhibit 1). For risk and compliance, as well as data governance, organizations often use a fully centralized model such as a center of excellence. For tech talent and adoption of AI solutions, on the other hand, respondents most often report using a hybrid or partially centralized model, with some resources handled centrally and others distributed across functions or business units-though respondents at organizations with less than $500 million in annual revenues are more likely than others to report fully centralizing these elements.

Web &lt;2024&gt;

In [8]:
import pandas as pd
chunks_df = pd.DataFrame(chunks)

chunks_df.head()

,chunk_id,section,heading,heading_level,text,source,word_count
0,chunk_0,The state of AI AI e of,The state of AI AI e of,2,How organizations are rewiring to capture valu...,/content/output_documents/converted_document_i...,208
1,chunk_1,The state of AI AI e of > How companies are or...,How companies are organizing their gen AI depl...,2,Our survey analyses show that a CEO's oversigh...,/content/output_documents/converted_document_i...,209
2,chunk_2,The state of AI AI e of > Twenty-eight percent...,Twenty-eight percent of respondents whose orga...,2,1 The correlation analyses considered 25 attri...,/content/output_documents/converted_document_i...,358
3,chunk_3,The state of AI AI e of > Twenty-eight percent...,Twenty-eight percent of respondents whose orga...,2,Twenty-one percent of respondents reporting ge...,/content/output_documents/converted_document_i...,234
4,chunk_4,The state of AI AI e of > Organizations are se...,Organizations are selectively centralizing ele...,2,The survey findings also shed light on how org...,/content/output_documents/converted_document_i...,112

In [9]:
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

documents = []

for chunk in chunks:

    documents.append(
        Document(
            page_content=chunk["text"],
            metadata={
                "chunk_id": chunk["chunk_id"],
                "section": chunk["section"],
                "heading": chunk["heading"],
                "heading_level": chunk["heading_level"],
                "source": chunk["source"],
                "word_count": chunk["word_count"]
            }
        )
    )

/tmp/ipykernel_1848/1678218973.py:3: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [10]:
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [11]:
vectorstore = FAISS.from_documents(
    documents,
    embedding_model
)

In [12]:
query = "How are companies organizing AI governance?"

results = vectorstore.similarity_search(
    query,
    k=5
)

In [13]:
for i, doc in enumerate(results):

    print("=" * 100)

    print("Rank:", i + 1)
    print("Chunk ID:", doc.metadata["chunk_id"])
    print("Section:", doc.metadata["section"])

    print("\nText:")
    print(doc.page_content)

====================================================================================================
Rank: 1
Chunk ID: chunk_1
Section: The state of AI AI e of > How companies are organizing their gen AI deploymentand who's in charge

Text:
Our survey analyses show that a CEO's oversight of AI governance-that is, the policies, processes, and technology necessary to develop and deploy AI systems responsibly-is one element most correlated with higher self-reported bottom-line impact from an organization's gen AI use. 1 That's particularly true at larger companies, where CEO oversight is the element with the most impact on EBIT attributable to gen AI. Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance, though the share is smaller at larger organizations with $500 million or more in annual revenues, and 17 percent say AI governance is overseen by their board of directors. In many cases, AI governance is jointly owned: On average, respondents report that two leaders are in charge.

The value of AI comes from rewiring how companies run, and the latest survey shows that, out of 25 attributes tested for organizations of all sizes, the redesign of workflows has the biggest effect on an organization's ability to see EBIT impact from its use of gen AI. Organizations are beginning to reshape their workflows as they deploy gen AI. Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.
====================================================================================================
Rank: 2
Chunk ID: chunk_4
Section: The state of AI AI e of > Organizations are selectively centralizing elements of their AI deployment

Text:
The survey findings also shed light on how organizations are structuring their AI deployment efforts. Some essential elements for deploying AI tend to be fully or partially centralized (Exhibit 1). For risk and compliance, as well as data governance, organizations often use a fully centralized model such as a center of excellence. For tech talent and adoption of AI solutions, on the other hand, respondents most often report using a hybrid or partially centralized model, with some resources handled centrally and others distributed across functions or business units-though respondents at organizations with less than $500 million in annual revenues are more likely than others to report fully centralizing these elements.

Web &lt;2024&gt;
====================================================================================================
Rank: 3
Chunk ID: chunk_0
Section: The state of AI AI e of

Text:
How organizations are rewiring to capture value

Alex Singla Alexander Sukharevsky Lareina Yee Michael Chui Bryce Hall

March 2025

Organizations are beginning to create the structures and processes that lead to meaningful value from gen AI. While still in early days, companies are redesigning workflows, elevating governance, and mitigating more risks.

<!-- image -->

rganizations are starting to make organizational changes designed to generate future value from gen AI, and large companies are leading the way. The latest McKinsey Global Survey on AI finds

that organizations are beginning to take steps that drive bottom-line impact-for example, redesigning workflows as they deploy gen AI and putting senior leaders in critical roles, such as overseeing AI governance. The findings also show that organizations are working to mitigate a growing set of gen-AI-related risks and are hiring for new AI-related roles while they retrain employees to participate in AI deployment. Companies with at least $500 million in annual revenue are changing more quickly than smaller organizations. Overall, the use of AI-that is, gen AI as well as analytical AI-continues to build momentum: More than three-quarters of respondents now say that their organizations use AI in at least one business function. The use of gen AI in particular is rapidly increasing.

O
====================================================================================================
Rank: 4
Chunk ID: chunk_3
Section: The state of AI AI e of > Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.

Text:
Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.

<!-- image -->

<!-- image -->

6

McKinsey commentary

Alexander Sukharevsky

Senior partner and global coleader of QuantumBlack, AI by McKinsey

The more we see organizations using AI, the more we recognize that it takes a topdown process to really move the needle. Effective AI implementation starts with a fully committed C-suite and, ideally, an engaged board. Many companies' instinct is to delegate implementation to the IT or digital department, but over and over again, this turns out to be a recipe for failure.

There are several reasons for this. The first is that getting real value out of AI requires transformation, not just new technology. It's a question of successful change management and mobilization, which is why C-suite leadership is essential. It's also a potentially expensive transformation, requiring intensive use of sometimes scarce resources and talent. A lot rides on how those resources are made available, and that's an executive-level call requiring nuanced decision-making that reflects the balance organizations must strike between efficient resource use and broad empowerment-a balance that must be constantly reevaluated as the technology and organization evolve.

As organizations become more fluent with AI, it will essentially become embedded in all functions, leaving leadership to focus on higher-level tasks like impact monitoring and talent development rather than on implementation.
====================================================================================================
Rank: 5
Chunk ID: chunk_2
Section: The state of AI AI e of > Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.

Text:
1 The correlation analyses considered 25 attributes and the reported effect of gen AI use on organizations' EBIT, and using the Johnson's Relative Weights regression analysis yielded an R-squared of 0.20. The attributes included which leaders oversee AI governance at organizations, how organizations are managing the time saved by gen AI deployment (for example, assigning completely new activities and fewer hours to employees, reducing head count), whether organizations have fundamentally redesigned at least some of their workflows as a result of gen AI deployment, and whether they have adopted each of 12 gen AI adoption and scaling best practices: 1) establishing a dedicated team to drive gen AI adoption (for example, a project management office, transformation office, or dedicated adoption and scaling team); 2) having regular internal communications about the value created by their gen AI solutions to build awareness and momentum; 3) having senior leaders who are actively engaged in driving gen AI adoption, including role modeling the use of gen AI; 4) embedding gen AI solutions into business processes effectively (for example, changing frontline employees' processes, creating user interfaces to incorporate gen AI solutions); 5) establishing role-based capability training courses to make sure employees at each level know how to use gen AI capabilities appropriately; 6) creating a comprehensive approach to foster trust among employees in our use of gen AI (for example, understanding primary sources, mitigating inaccuracies); 7) having a mechanism to incorporate feedback on the performance of gen AI solutions and improve them over time; 8) establishing a clearly defined road map to drive adoption of gen AI solutions (for example, with phased rollouts across teams and business units); 9) establishing a compelling change story about the need for gen AI adoption; 10) tracking well-defined KPIs for gen AI solutions, enabling insights into their adoption and ROI; 11) establishing employee incentives that reinforce gen AI adoption; and 12) creating a comprehensive approach to foster trust among customers in our use of gen AI (for example, transparency on regulatory compliance, use of customer data).

Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.

###Retriever Construction

In [14]:
# ---------------------------------------------------------
# Retriever
# ---------------------------------------------------------

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5}
)


def retrieve_text(query, k=5):

    # Update k dynamically
    retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={"k": k}
    )

    results = retriever.invoke(query)

    return "\n\n".join(
        doc.page_content for doc in results)

In [15]:
query = "Who is responsible for overseeing AI governance?"

response = retrieve_text(query, k=5)

print(response)

Our survey analyses show that a CEO's oversight of AI governance-that is, the policies, processes, and technology necessary to develop and deploy AI systems responsibly-is one element most correlated with higher self-reported bottom-line impact from an organization's gen AI use. 1 That's particularly true at larger companies, where CEO oversight is the element with the most impact on EBIT attributable to gen AI. Twenty-eight percent of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance, though the share is smaller at larger organizations with $500 million or more in annual revenues, and 17 percent say AI governance is overseen by their board of directors. In many cases, AI governance is jointly owned: On average, respondents report that two leaders are in charge.

The value of AI comes from rewiring how companies run, and the latest survey shows that, out of 25 attributes tested for organizations of all sizes, the redesign of workflows has the biggest effect on an organization's ability to see EBIT impact from its use of gen AI. Organizations are beginning to reshape their workflows as they deploy gen AI. Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.

How organizations are rewiring to capture value

Alex Singla Alexander Sukharevsky Lareina Yee Michael Chui Bryce Hall

March 2025

Organizations are beginning to create the structures and processes that lead to meaningful value from gen AI. While still in early days, companies are redesigning workflows, elevating governance, and mitigating more risks.

<!-- image -->

rganizations are starting to make organizational changes designed to generate future value from gen AI, and large companies are leading the way. The latest McKinsey Global Survey on AI finds

that organizations are beginning to take steps that drive bottom-line impact-for example, redesigning workflows as they deploy gen AI and putting senior leaders in critical roles, such as overseeing AI governance. The findings also show that organizations are working to mitigate a growing set of gen-AI-related risks and are hiring for new AI-related roles while they retrain employees to participate in AI deployment. Companies with at least $500 million in annual revenue are changing more quickly than smaller organizations. Overall, the use of AI-that is, gen AI as well as analytical AI-continues to build momentum: More than three-quarters of respondents now say that their organizations use AI in at least one business function. The use of gen AI in particular is rapidly increasing.

O

1 The correlation analyses considered 25 attributes and the reported effect of gen AI use on organizations' EBIT, and using the Johnson's Relative Weights regression analysis yielded an R-squared of 0.20. The attributes included which leaders oversee AI governance at organizations, how organizations are managing the time saved by gen AI deployment (for example, assigning completely new activities and fewer hours to employees, reducing head count), whether organizations have fundamentally redesigned at least some of their workflows as a result of gen AI deployment, and whether they have adopted each of 12 gen AI adoption and scaling best practices: 1) establishing a dedicated team to drive gen AI adoption (for example, a project management office, transformation office, or dedicated adoption and scaling team); 2) having regular internal communications about the value created by their gen AI solutions to build awareness and momentum; 3) having senior leaders who are actively engaged in driving gen AI adoption, including role modeling the use of gen AI; 4) embedding gen AI solutions into business processes effectively (for example, changing frontline employees' processes, creating user interfaces to incorporate gen AI solutions); 5) establishing role-based capability training courses to make sure employees at each level know how to use gen AI capabilities appropriately; 6) creating a comprehensive approach to foster trust among employees in our use of gen AI (for example, understanding primary sources, mitigating inaccuracies); 7) having a mechanism to incorporate feedback on the performance of gen AI solutions and improve them over time; 8) establishing a clearly defined road map to drive adoption of gen AI solutions (for example, with phased rollouts across teams and business units); 9) establishing a compelling change story about the need for gen AI adoption; 10) tracking well-defined KPIs for gen AI solutions, enabling insights into their adoption and ROI; 11) establishing employee incentives that reinforce gen AI adoption; and 12) creating a comprehensive approach to foster trust among customers in our use of gen AI (for example, transparency on regulatory compliance, use of customer data).

Twenty-one percent of respondents reporting gen AI use by their organizations say their organizations have fundamentally redesigned at least some workflows.

The survey findings also shed light on how organizations are structuring their AI deployment efforts. Some essential elements for deploying AI tend to be fully or partially centralized (Exhibit 1). For risk and compliance, as well as data governance, organizations often use a fully centralized model such as a center of excellence. For tech talent and adoption of AI solutions, on the other hand, respondents most often report using a hybrid or partially centralized model, with some resources handled centrally and others distributed across functions or business units-though respondents at organizations with less than $500 million in annual revenues are more likely than others to report fully centralizing these elements.

Web &lt;2024&gt;

This survey also examines the state of AI-related hiring and other ways AI affects the workforce. Respondents working for organizations that use AI are about as likely as they were in the early 2024 survey to say their organizations hired individuals for AI-related roles in the past 12 months. The only roles that differ this year are data-visualization and design specialists, which respondents are significantly less likely than in the previous survey to report hiring. The findings also indicate several new risk-related roles that are becoming part of organizations' AI deployment processes. Thirteen percent of respondents say their organizations have hired AI compliance specialists, and 6 percent report hiring AI ethics specialists. Respondents at larger companies are more likely than their peers at smaller organizations to report hiring a broad range of AI-related roles, with the largest gaps seen in hiring AI data scientists, machine learning engineers, and data engineers.

###RAG Pipeline

In [28]:
import os
from getpass import getpass
os.environ["OPENAI_API_KEY"] = getpass("Enter your Open API key: ")

Enter your Open API key: ··········

In [35]:
from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="llama3.2",
    temperature=0
)

In [36]:
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_template("""
You are a question-answering assistant.

Answer the user's question using ONLY the information
provided in the context below.

If the answer cannot be found in the context, say:
"I don't have enough information in the provided document."

Do not make up information.

Context:
----------------
{context}
----------------

Question:
{question}

Answer:
""")

In [37]:
def rag_answer(query, k=5):

    # -----------------------------------------
    # 1. Retrieve relevant chunks
    # -----------------------------------------

    retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={"k": k}
    )

    retrieved_docs = retriever.invoke(query)

    # -----------------------------------------
    # 2. Combine retrieved chunks
    # -----------------------------------------

    context = "\n\n".join(
        doc.page_content
        for doc in retrieved_docs
    )

    # -----------------------------------------
    # 3. Create prompt
    # -----------------------------------------

    messages = prompt.format_messages(
        context=context,
        question=query
    )

    # -----------------------------------------
    # 4. Generate answer
    # -----------------------------------------

    response = llm.invoke(messages)

    # -----------------------------------------
    # 5. Return only the answer
    # -----------------------------------------

    return response.content

In [40]:
# First, install zstd, a dependency for Ollama extraction
!apt-get update && apt-get install -y zstd

# Then, install Ollama in the Colab environment.
# This will download the Ollama binary and install it to /usr/local/bin
!curl -fsSL https://ollama.com/install.sh | sh

# Add Ollama to the PATH for the current session if it's not already there
import os
if '/usr/local/bin' not in os.environ['PATH']:
    os.environ['PATH'] += os.pathsep + '/usr/local/bin'

# Start the Ollama server in the background
import subprocess
import time

print("Attempting to start Ollama server...")
# Use nohup and & to run Ollama server in the background
# Redirect stdout/stderr to a file to prevent hanging
os.system('nohup ollama serve > ollama.log 2>&1 &')
print("Ollama server command issued. Waiting for server to start...")

# Wait a moment for the server to start and become responsive
time.sleep(10) # Increased sleep time for server startup

# Verify Ollama is running and pull the specific model
try:
    print("Verifying Ollama server status...")
    subprocess.run(['ollama', 'list'], check=True, capture_output=True)
    print("Ollama server is running.")

    print("Pulling Ollama model 'llama3.2'...")
    subprocess.run(['ollama', 'pull', 'llama3.2'], check=True, capture_output=False) # Capture output=False to show progress
    print("Ollama model 'llama3.2' pulled successfully.")
except (subprocess.CalledProcessError, FileNotFoundError) as e:
    print(f"Error with Ollama server or model pull: {e}")
    print("Check ollama.log for details if server failed to start.")
    # Attempt to print log for debugging
    if os.path.exists('ollama.log'):
        with open('ollama.log', 'r') as f:
            print("--- ollama.log ---")
            print(f.read())
            print("------------------")

Hit:1 https://cli.github.com/packages stable InRelease
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,578 B]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [107 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,908 kB]
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,164 kB]
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,199 kB]
Hit:14 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:15 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,848 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,314 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,557 kB]
Get:19 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.7 MB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,532 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,616 kB]
Fetched 44.4 MB in 6s (8,063 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 69 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 2s (319 kB/s)
Selecting previously unselected package zstd.
(Reading database ... 122492 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...
>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
Attempting to start Ollama server...
Ollama server command issued. Waiting for server to start...
Verifying Ollama server status...
Ollama server is running.
Pulling Ollama model 'llama3.2'...
Ollama model 'llama3.2' pulled successfully.
According to the survey, 28% of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.

In [41]:
# Now, the original code to run the RAG query
query = "Who is responsible for overseeing AI governance?"

answer = rag_answer(query)

print(answer)

According to the survey, 28% of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.

###Evaluation

In [42]:
import pandas as pd
from IPython.display import display


# ============================================================
# 1. Evaluation queries
# ============================================================

test_queries = [
    "Who is responsible for overseeing AI governance?",

    "How are organizations redesigning workflows to capture value from generative AI?",

    "How widely are organizations using AI across business functions?",

    "What risks related to generative AI are organizations trying to mitigate?",

    "What new AI-related roles and skills are organizations developing?"
]


# ============================================================
# 2. RAG function
# ============================================================

def rag_answer(query, k=5):

    # Retrieve relevant chunks
    docs = retriever.invoke(query)

    # Keep only top-k
    docs = docs[:k]

    # Combine retrieved chunks into context
    context = "\n\n".join(
        doc.page_content
        for doc in docs
    )

    # RAG prompt
    prompt = f"""
You are a question-answering assistant.

Answer the question using ONLY the information
provided in the context below.

If the answer cannot be found in the context,
say: "I don't have enough information in the provided document."

Do not make up information.

Context:
-------------------------
{context}
-------------------------

Question:
{query}

Answer:
"""

    # Generate answer
    response = llm.invoke(prompt)

    return response.content, docs


# ============================================================
# 3. Run evaluation queries
# ============================================================

evaluation_results = []

for i, query in enumerate(test_queries, start=1):

    answer, retrieved_docs = rag_answer(
        query,
        k=5
    )

    evaluation_results.append({
        "Query": query,
        "Answer": answer,
        "Retrieved_Docs": retrieved_docs
    })


# ============================================================
# 4. Display generated answers
# ============================================================

for i, result in enumerate(evaluation_results, start=1):

    print("=" * 100)
    print(f"QUERY {i}")
    print("=" * 100)

    print("\nQuestion:")
    print(result["Query"])

    print("\nGenerated Answer:")
    print(result["Answer"])

    print()


# ============================================================
# 5. Manual evaluation
# ============================================================
#
# Relevance:
# 5 = Directly answers the question
# 4 = Mostly answers the question
# 3 = Partially answers
# 2 = Mostly irrelevant
# 1 = Completely irrelevant
#
# Accuracy:
# 5 = Fully supported by the document
# 4 = Mostly supported
# 3 = Partially supported
# 2 = Significant errors
# 1 = Incorrect / unsupported
#
# IMPORTANT:
# Change these scores after examining the actual answers.
# ============================================================

evaluation_scores = [
    {
        "Query": test_queries[0],
        "Relevance": 5,
        "Accuracy": 5,
        "Comments": "Answer directly addresses AI governance responsibility."
    },
    {
        "Query": test_queries[1],
        "Relevance": 5,
        "Accuracy": 5,
        "Comments": "Answer discusses workflow redesign and its role in capturing value."
    },
    {
        "Query": test_queries[2],
        "Relevance": 5,
        "Accuracy": 5,
        "Comments": "Answer addresses AI adoption across business functions."
    },
    {
        "Query": test_queries[3],
        "Relevance": 4,
        "Accuracy": 4,
        "Comments": "Answer covers risks discussed in the retrieved context."
    },
    {
        "Query": test_queries[4],
        "Relevance": 4,
        "Accuracy": 5,
        "Comments": "Answer is supported by the report's discussion of AI roles and skills."
    }
]


# ============================================================
# 6. Create evaluation table
# ============================================================

evaluation_df = pd.DataFrame(evaluation_scores)

display(evaluation_df)


# ============================================================
# 7. Calculate average scores
# ============================================================

average_relevance = evaluation_df["Relevance"].mean()
average_accuracy = evaluation_df["Accuracy"].mean()

print("\nEvaluation Summary")
print("-" * 40)
print(f"Average Relevance : {average_relevance:.2f} / 5")
print(f"Average Accuracy  : {average_accuracy:.2f} / 5")

====================================================================================================
QUERY 1
====================================================================================================

Question:
Who is responsible for overseeing AI governance?

Generated Answer:
According to the context, 28% of respondents whose organizations use AI report that their CEO is responsible for overseeing AI governance.

====================================================================================================
QUERY 2
====================================================================================================

Question:
How are organizations redesigning workflows to capture value from generative AI?

Generated Answer:
Organizations are redesigning workflows to capture value from generative AI by making changes such as putting senior leaders in critical roles, such as overseeing AI governance, and redesigning workflows as they deploy gen AI.

====================================================================================================
QUERY 3
====================================================================================================

Question:
How widely are organizations using AI across business functions?

Generated Answer:
According to the report, 78 percent of respondents say their organizations use AI in at least one business function, up from 72 percent in early 2024 and 55 percent a year earlier. Additionally, for the first time, most survey respondents report the use of AI in more than one business function.

====================================================================================================
QUERY 4
====================================================================================================

Question:
What risks related to generative AI are organizations trying to mitigate?

Generated Answer:
According to the context, organizations are trying to mitigate the following gen-AI-related risks:

1. Inaccuracy
2. Cybersecurity
3. Intellectual property infringement

These risks are among the ones that respondents most commonly say have caused negative consequences for their organizations.

====================================================================================================
QUERY 5
====================================================================================================

Question:
What new AI-related roles and skills are organizations developing?

Generated Answer:
According to the context, organizations are developing several new AI-related roles and skills, including:

1. AI compliance specialists
2. AI ethics specialists
3. Data-visualization and design specialists (although respondents are less likely to report hiring these roles compared to previous surveys)
4. Data scientists
5. Machine learning engineers
6. Data engineers

These roles are becoming part of organizations' AI deployment processes, and larger companies are more likely to report hiring a broader range of AI-related roles compared to smaller organizations.

,Query,Relevance,Accuracy,Comments
0,Who is responsible for overseeing AI governance?,5,5,Answer directly addresses AI governance respon...
1,How are organizations redesigning workflows to...,5,5,Answer discusses workflow redesign and its rol...
2,How widely are organizations using AI across b...,5,5,Answer addresses AI adoption across business f...
3,What risks related to generative AI are organi...,4,4,Answer covers risks discussed in the retrieved...
4,What new AI-related roles and skills are organ...,4,5,Answer is supported by the report's discussion...

Evaluation Summary
----------------------------------------
Average Relevance : 4.60 / 5
Average Accuracy  : 4.80 / 5